### ISSUE TITLE
Incorrect IR generation for IMUL

### ISSUE THREAD

**Issue by mrexodia** [yegord/snowman#11]
I just put the entire section of ntdll.dll x64 in snowman (through the x64dbg module), and it crashes [here](https://github.com/yegord/snowman/blob/master/src/nc/core/ir/Terms.cpp#L149)

Any idea what it could be?

**Comment by yegord** [comment]
Most likely, some instruction tries to generate an IR expression with the BinaryOperator getting operands of different sizes. You can infer the instruction from the call stack dump (from the line in X86InstructionAnalyzer.cpp), you can print it using the debugger or just by inserting something like `std::cerr << instruction->toString().toStdString() << std::endl;` in a proper place.

If you use the latest version in master, the assert may fail because Capstone reports some operand size differently from libudis86, in this case, please fix the IR code generation or send the faulty instruction to me. If this is not in the latest version of master, you can try to upgrade to the latest master.

**Comment by mrexodia** [comment]
I'll try to find the instruction

**Comment by yegord** [comment]
Should be fixed in 5d095c2ca015985441e8e7eb972d55efac9f9bac.

**Comment by mrexodia** [comment]
Hi, 

The error is the same and it comes from x86instructionalayzer.cpp line 540 (inside the imul instruction)

**Comment by yegord** [comment]
Hi! Could you please provide the exact file on which the assertion fails?

**Comment by mrexodia** [comment]
it is `ntdll.dll` 64 bit version, but it will crash when you try to open it with `snowman.exe`. I use x64dbg and directly disassemble the entire code section.

**Comment by yegord** [comment]
Well, I found some 64-bit ntdll.dll, and the decompiler does not crash on it. Could you give me the exact file on which you observe the crash?

**Comment by mrexodia** [comment]
Here you go: https://mega.co.nz/#!69hEACbJ!xtO6IRFsAXhFiqtzJ5FMPTP-W4QZ6tiEZP3J_tAAzR0

I use snowman x64 on windows. Just open the file (disassembling will go fine). Then press 'Decompile' and it will crash.

**Comment by yegord** [comment]
Related: https://github.com/aquynh/capstone/issues/392
