### ISSUE TITLE
Suggestion: Statically link dependencies for standalone versions

### ISSUE THREAD

**Issue by saxbophone** [yegord/snowman#113]
I downloaded one of the standalone Windows packages from here: https://derevenets.com/files/snowman-v0.1.0-win-x86.7z

Running it in Wine (just out of curiosity) showed it couldn't find the dependency DLLs, which I can see are distributed in the archive linked above. - That's no big deal as I know in any case, those DLLs would need to be in my PATH to work, however I'd like to suggest you consider statically linking your dependencies into one single executable.

Of course, this would make the size of said executable grow rather large, but then again currently you need to distribute the dependencies anyway so I imagine the size difference would not be too extreme. The benefit would be having one single portable file which works on its own.

It would be good to know your thoughts on this, and sorry if this is something you've already considered!

**Comment by yegord** [comment]
According to MSDN [1], the application directory is searched for DLLs
first, so, everything should just work. And it actually works for me with
Wine on Debian Testing. If you need help with running Snowman in Wine,
please report your OS and Wine versions, the exact steps to reproduce the
problem, and the error message.

Concerning static linking, it will increase the size of the distribution,
because both executables need to be linked against QtCore. And I am
reluctant to spend time on updating the build scripts, rebuilding Qt on the
build server, testing without being sure that the problem exists.

[1]
https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms682586(v=vs.85).aspx

-- 
Yegor Derevenets

**Comment by saxbophone** [comment]
Ok Yegor, that sounds good. I'll do some further testing of my own but I am
now sceptical as you are that this will have any major benefits in relation
to its cost.

Also, I just took a look at the size of the Qt DLL... I can totally see why
you want to avoid statically linking that!
