### ISSUE TITLE
Decompile only function

### ISSUE THREAD

**Issue by s0i37** [yegord/snowman#162]
Hello.
How can I do to decompile only one function like a ida-plugin.
I want to decompile in radare2 through nocode.

**Comment by yegord** [comment]
At the moment nocode does not provide an interface for decompiling a part of the program.
However, it should be easy to implement.
Instead of disassembling the whole program in https://github.com/yegord/snowman/blob/562bfcad0a29c70667adad0db83c960f786fee5e/src/nocode/main.cpp#L257 you need to call `Driver::disassemble(context, section, start, end)` for each section and the [start, end) region of addresses in this section belonging to the function.
What remains is to add support for passing the addresses to be decompiled on the command line.
Feel free to make a pull request in case you implement it.

**Comment by s0i37** [comment]
Ok thanks

**Comment by s0i37** [comment]
see Pull request #164

**Comment by yegord** [comment]
I guess, it should be closed now.
