### ISSUE TITLE
Multiplication dropped in decompiled program

### ISSUE THREAD

**Issue by jrmuizel** [yegord/snowman#30]
The following program is not properly decompiled when compiled for x86-64 with clang (Apple LLVM version 6.0)
```c
long f(int x)
{
        long l = 0;
        while (x)
        {
                l *= l;
                l += x;
                x--;
        }
        return l;
}
```
```
_f:
pushq	%rbp
movq	%rsp, %rbp
xorl	%eax, %eax
testl	%edi, %edi
je	0x37
movslq	%edi, %rcx
incq	%rcx
xorl	%edx, %edx
nopw	%cs:_f(%rax,%rax)
movq	%rdx, %rax
imulq	%rax, %rax
decl	%edi
leaq	-0x1(%rcx,%rax), %rdx
leaq	-0x1(%rcx), %rcx
jne	0x20
addq	%rcx, %rax
popq	%rbp
retq
```
http://people.mozilla.org/~jmuizelaar/snowman/f.o

**Comment by hlide** [comment]
1) when inserting C++ code in your post, could you use [the Syntax Highlighting](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) with *c++* instead of *javascript* as given in the example code?

2) Could you give the assembly result (using *code block* as well)?

3) Could you give the *C++* output of *snowman* as well?

**Comment by nihilus** [comment]
Actually this is a recent bug... Got the same issue with MIPS.

**Comment by nihilus** [comment]
Not necessarily the same source code

**Comment by yegord** [comment]
It was a nice example: it revealed that the decompiler generated incorrected IR for some memory operands. Thanks!
