### ISSUE TITLE
hi yegord.this is VVV/99 edx12=edx but how to rebuild (__intrinsic() function in VS2015?

### ISSUE THREAD

**Issue by ddkwork** [yegord/snowman#95]
hi yegord.

43781e: mov eax, 0x30c30c31
437823: imul edi
437825: sar edx, 0x2
437828: mov eax, edx

edx12 = (uint32_t)(__intrinsic() >> 2); ??
this is VVV/99 edx12=edx but how to rebuild (__intrinsic() function in VS2015?

void fun_4377a4() {
uint32_t eax1 = 0;
uint32_t ebp2 = {0x609f};
int32_t ebp3 = 0;
uint32_t edi4 = 0;
uint32_t eax5 = 0;
uint32_t esi6 = 0;
uint32_t edi7 = 0;
uint32_t ecx8 = 0;
uint32_t edx9 = 0;
int32_t esi10 = 0;
uint32_t edx11 = 0;
uint32_t edx12 = 0;
uint32_t eax13 = 0;
uint32_t ecx14 = 0;
uint32_t esi15 = 0;
uint32_t esi16 = 0;
uint32_t v17 = 0;
uint32_t eax18 = 0;
uint32_t edx19 = 0;
uint32_t eax20 = 0;
uint32_t edi21 = 0;
uint32_t ecx22 = 0;
uint32_t eax23 = 0;
uint32_t v24 = 0;
uint32_t eax25 = 0;
uint32_t eax26 = 0;
//int1_t zf27;
//struct s0\* ebx28;

eax1 = ((ebp2 & 0xffff) + (ebp3 >> 16) & 0xffff) + edi4;
eax5 = esi6 ^ edi7;
ecx8 = (((int32_t)eax1 >> 16) + (eax1 & 0xffff) & 0xffff) + (((int32_t)eax5 >> 16) + (eax5 & 0xffff) & 0xffff);
//edx9 = (uint32_t)(__intrinsic() + esi10 >> 6);
//edx11 = (uint32_t)(__intrinsic() >> 1);
//edx12 = (uint32_t)(__intrinsic() >> 2);
eax13 = (edx12 >> 31) + ((edx11 >> 31) + ((edx9 >> 31) + edx9 + edx11) + edx12);
ecx14 = (((int32_t)ecx8 >> 16) + (ecx8 & 0xffff) & 0xffff) + (((int32_t)eax13 >> 16) + (eax13 & 0xffff) & 0xffff);
esi15 = esi16 ^ v17;
eax18 = (((int32_t)ecx14 >> 16) + (ecx14 & 0xffff) & 0xffff) + ((esi15 & 0xffff) + ((int32_t)esi15 >> 16) & 0xffff);
edx19 = v17 & 0xff;
eax20 = ((edi21 & 0xff) + 0xd3) \* (edx19 + 1);
ecx22 = (((int32_t)eax18 >> 16) + (eax18 & 0xffff) & 0xffff) + (((int32_t)eax20 >> 16) + (eax20 & 0xffff) & 0xffff);
eax23 = ((v24 & 0xff) + 11) \* (edx19 + 17);
eax25 = (((int32_t)eax23 >> 16) + (eax23 & 0xffff) & 0xffff) + ((ecx22 & 0xffff) + ((int32_t)ecx22 >> 16) & 0xffff);
//eax26 = fun_4b5442(4, __return_address());
eax26 = ((int32_t)eax25 >> 16) + (eax25 & 0xffff) & 0xffff;
W4 = eax26;
// zf27 = ebx28->f16 == 0;
// if (!zf27) {
// }
}

//edx9 = (uint32_t)(__intrinsic() + esi10 >> 6);
//edx11 = (uint32_t)(__intrinsic() >> 1);
//edx12 = (uint32_t)(__intrinsic() >> 2);
)(__intrinsic() ????

my email is:13529219617@qq.com thank you

//uint32_t\* fun_4b5442(int32_t a1, int32_t a2);

//struct s0 {
// int8_t[16] pad16;
// int32_t f16;
//};
# include
# include

// pragma_directive_intrinsic.cpp
//#include // definitions for _disable, _enable
//#pragma intrinsic(_disable)
//#pragma intrinsic(_enable)
# include

int W4;

void fun_4377a4() {
uint32_t eax1 = 0;
uint32_t ebp2 = 0;
int32_t ebp3 = 0;
uint32_t edi4 = 0;
uint32_t eax5 = 0;
uint32_t esi6 = 0;
uint32_t edi7 = 0;
uint32_t ecx8 = 0;
uint32_t edx9 = 0;
int32_t esi10 = 0;
uint32_t edx11 = 0;
uint32_t edx12 = 0;
uint32_t eax13 = 0;
uint32_t ecx14 = 0;
uint32_t esi15 = 0;
uint32_t esi16 = 0;
uint32_t v17 = 0;
uint32_t eax18 = 0;
uint32_t edx19 = 0;
uint32_t eax20 = 0;
uint32_t edi21 = 0;
uint32_t ecx22 = 0;
uint32_t eax23 = 0;
uint32_t v24 = 0;
uint32_t eax25 = 0;
uint32_t eax26 = 0;
// int1_t zf27;
// struct s0\* ebx28;
ebp2 = 0x0000609F;
esi6 = 0x00004BBB;
eax1 = ((ebp2 & 0xffff) + (ebp3 >> 16) & 0xffff) + edi4;
eax5 = esi6 ^ edi7;
ecx8 = (((int32_t)eax1 >> 16) + (eax1 & 0xffff) & 0xffff) + (((int32_t)eax5 >> 16) + (eax5 & 0xffff) & 0xffff);
edx9 = (uint32_t)(__intrinsic() + esi10 >> 6);
edx11 = (uint32_t)(__intrinsic() >> 1);
edx12 = (uint32_t)(__intrinsic() >> 2);
eax13 = (edx12 >> 31) + ((edx11 >> 31) + ((edx9 >> 31) + edx9 + edx11) + edx12);
ecx14 = (((int32_t)ecx8 >> 16) + (ecx8 & 0xffff) & 0xffff) + (((int32_t)eax13 >> 16) + (eax13 & 0xffff) & 0xffff);
esi15 = esi16 ^ v17;
eax18 = (((int32_t)ecx14 >> 16) + (ecx14 & 0xffff) & 0xffff) + ((esi15 & 0xffff) + ((int32_t)esi15 >> 16) & 0xffff);
edx19 = v17 & 0xff;
eax20 = ((edi21 & 0xff) + 0xd3) \* (edx19 + 1);
ecx22 = (((int32_t)eax18 >> 16) + (eax18 & 0xffff) & 0xffff) + (((int32_t)eax20 >> 16) + (eax20 & 0xffff) & 0xffff);
eax23 = ((v24 & 0xff) + 11) \* (edx19 + 17);
eax25 = (((int32_t)eax23 >> 16) + (eax23 & 0xffff) & 0xffff) + ((ecx22 & 0xffff) + ((int32_t)ecx22 >> 16) & 0xffff);
//eax26 = fun_4b5442(4, __return_address());
eax26 = ((int32_t)eax25 >> 16) + (eax25 & 0xffff) & 0xffff;
W4 = eax26;
}
int main(void)
{
fun_4377a4();
printf("%04X\n", W4);
getchar();

}

**Comment by yegord** [comment]
Hi, intrinsics are used in IR to denote a value that is computed somehow, but nobody bothered to specify, how exactly. So, if you see them, but do not want to, you should look at the instruction where they come from, go to the source code (X86InstructionAnalyzer), complete the instruction semantics' description (replace intrinsic() with something more specific), and ideally submit a patch.

**Comment by DiskGetor** [comment]
please look at my video for show the bug for Replace “__intrinsic()”.

link：
http://pan.baidu.com/s/1hr7zqok

**Comment by DiskGetor** [comment]
@yegord 

#include <stdio.h>
#include <windows.h>
#include <stdint.h>

int W3;

void fun_437589() {
	uint32_t ecx1;
	uint32_t edi2=0x42D2;
	uint32_t esi3=0;
	uint32_t eax4=0;
	uint32_t esi5=0x609F;
	uint32_t edi6=0;
	uint32_t ecx7=0;
	uint32_t eax8=0;
	uint32_t esi9=0;
	uint32_t edi10=0;
	uint32_t ecx11=0;
	uint32_t edx12=0;
	int32_t esi13=0;
	uint32_t edx14=0;
	int32_t edi15=0;
	uint32_t eax16=0;
	uint32_t ecx17=0;
	uint32_t esi18=0;
	uint32_t esi19=0;
	uint32_t edi20=0;
	uint32_t eax21=0;

	ecx1 = (edi2 & 0x67f2 & 0xffff & 0xffff & 0xffff & 0xffff) + (esi3 & 0x5238 & 0xffff & 0xffff);
	eax4 = esi5 ^ edi6;
	ecx7 = (((int32_t)ecx1 >> 16) + (ecx1 & 0xffff) & 0xffff) + (((int32_t)eax4 >> 16) + (eax4 & 0xffff) & 0xffff);
	//eax8 = esi9 & edi10;
	//ecx11 = (((int32_t)ecx7 >> 16) + (ecx7 & 0xffff) & 0xffff) + (((int32_t)eax8 >> 16) + (eax8 & 0xffff) & 0xffff);
	ecx11 = ((((int32_t)ecx7 >> 16) + (ecx7 & 0xffff) & 0xffff) + (((int32_t)eax8 >> 16) + (eax8 & 0xffff) & 0xffff))/ 105;
	//edx12 = (uint32_t)(__intrinsic() + esi13 >> 6);
	//edx14 = (uint32_t)(__intrinsic() + edi15 >> 4);     this is wrong.

	//v95 = ((W1 + ((-2078209981i64 * W1) >> 32)) >> 4) + W2 / 105; //from IDA F5 was link right result the W4=0x4BBB
	eax16 = (edx14 >> 31) + ((edx12 >> 31) + edx12 + edx14);
	ecx17 = (((int32_t)ecx11 >> 16) + (ecx11 & 0xffff) & 0xffff) + (((int32_t)eax16 >> 16) + (eax16 & 0xffff) & 0xffff);
	esi18 = esi19 | edi20;
	eax21 = ((ecx17 & 0xffff) + ((int32_t)ecx17 >> 16) & 0xffff) + ((esi18 & 0xffff) + ((int32_t)esi18 >> 16) & 0xffff);
	//if ((int32_t)(((int32_t)eax21 >> 16) + (eax21 & 0xffff) & 0xffff) >= (int32_t)10) {
	// }
	W3=((int32_t)eax21 >> 16) + (eax21 & 0xffff) & 0xffff;
}

	int main(void)
	{
		fun_437589();
		printf("%04X\n",W3);
		getchar();

	}

**Comment by DiskGetor** [comment]
snowman bug explains the division, the remainder of a division is interpreted as a function code: __intrinsic (bug.); this is great
Example：
<stdio.h> #include
Main int ()
{
Int a;
Int b;
B = rand ();
A = b/99;
Printf ("B =%d,%d a=, B",, a);
Getchar ();
}
Reference：
Https://blogs.msdn.micro

**Comment by DiskGetor** [comment]
@yegord 
__intrinsic() 
http://blog.csdn.net/ymlbright/article/details/22162951

This is what I saw today to crack a crackme
EAX ESI, XOR
ESP ADD, 8
ECX EAX, MOV
EAX MOV, 55555556
ECX IMUL
EAX EDX, MOV
ESI POP
EAX 1F, SHR
EDX EAX, ADD
Due to the lack of technology, the compilation is not familiar with, converted into the following expressions, found not to count, then Google 15890084????????????????????????????????????????????????????????????????
Found that the original is the VC compiler to optimize the division for the multiplication of the results, very easy to understand, posted two to me to help a lot of post t-68849.html? Http://bbs.pediy.com/archive/index.php
Http://www.cppblog.com/huyutian/articles/124742.html
And make a backup as follows:
Debugging a program today, encountered a strange compilation of code
Eax 68DB8BADh, mov
EDI push
ECX word, PTR [esi+0Eh] movsx
ECX imul
EDX 0Ch, SAR
Eax EDX, mov
Eax 1Fh, SHR
EDX eax, add
Look for a long time did not understand, is this 68DB8BADh is very awkward, and before and after the code is not associated in logic. To the Internet search, but also actually found the answer. It turned out to be a section of the compiler to optimize the multiplication operation of the typical code. As we all know, division is the most consumed CPU, can be converted into equivalent multiplication is much faster. But not every division can be optimized. For some specific numbers as dividend, this optimization is very effective.
Http://www.thesolver.it/Manuali/Factotum/source/076.htm here lists some typical number of division conversion tables.
This table is the 32 bit operations division conversion to a number of cases of multiplication. For example 68DB8BADh this magic number is used to convert divided by 625. To calculate x/625 = (68DB8BADh * x) >>8. so the code above is actually calculated +0Eh] [esi / 10000
The following table is a 64 bit algorithm for the multiplication of the division into a number of magic numbers, excerpts from this, in order to prevent forgetting
If you want to find out the relevant principles of operation can be seen on the site of the Chapter 10 Division by Constants Integer, the web site is http://www.thesolver.it/Manuali/Factotum/source/062.htm
We can also make up a small program to verify the.
1 <stdio.h> #include
Two
3 main int (argc int, argv[] char*)
{4
5 a getchar = int ();
6 B int = A / 10000;
7 printf ("a=%d\nb=a/10000=%d\n", a, B);
8 return 0;
9}
Ten
Set the project under the VC2008 compiler properties Output Assembler, select the output assembly code, see the compiled code and the above is completely consistent.
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- ---
<stdio.h> #include
Main int ()
{
Int a;
Int b;
B = rand ();
A = b/9;
Printf ("B =%d,%d a=, B",, a);
Getchar ();
}
.text:00401000; __cdecl main int (argc const, char **argv const, char *envp int)
_main proc near CODE; XREF: start+AFp.Text:00401000
E8 0E call 020000 _rand.Text:00401000
8B C8 mov ECX.Text:00401005, eax
B8.Text:00401007 39 E3 mov 38 eax 38E38E39h, 8E
F7 E9 imul ECX.Text:0040100C
D1 FA SAR EDX.Text:0040100E, 1
8B C2 mov eax.Text:00401010, EDX
C1 E8 1F SHR eax.Text:00401012, 1Fh
.text:00401015 03 add EDX D0, eax
.text:00401017 52 EDX push
.text:00401018 51 ECX push
.text:00401019 6830704000 offset????????????????????????????? A=????????? Push????? $DN????????????? _C@_0O@DGOM@b?????????"
E8 BF call 010000 _printf.Text:0040101E
The rule is:
The dividend increase X times to get a 2^N.
The division is multiplied by the divisor is X, then the right N.
A/B = /BX = AX = N "AX
For example, divided by 3,
Will be multiplied by 0xAAAAAAAB, and then shift
The efficiency of hardware divider, less than minus than multiplication, at least several times slower.
Study on the current hardware multiplier has been quite mature, such as of Leibniz's tree is very common for the design of parallel addition fast multiplier, good multiplier, such as many DSP multiply add unit, water can be completed in one period (of course is a multiplication multiplier pipeline in the ideal state, usually under), a multiplication instruction can be completed in 4~8 period.
But the divider to complete a division operation in today's super optimized hardware, but also need at least ten cycles.
With the multiplication of the division of the approximation algorithm, in the library and the compiler can be seen everywhere. If the compiler is configured to optimize at maximum speed, the compiler is likely to perform this optimization. And if the minimum volume optimization, may use the hardware division instruction.
The original turn from: http://blog.sina.com.cn/s/blog_62d718780100mqmm.html

**Comment by DiskGetor** [comment]
![image](https://cloud.githubusercontent.com/assets/19886504/19624998/7eec9044-993e-11e6-934b-cc98e49c705c.png)
![image](https://cloud.githubusercontent.com/assets/19886504/19625001/9672a4f6-993e-11e6-9161-e459a93bcad9.png)

**Comment by mrexodia** [comment]
I have implemented the semantics for the higher multiplication, but it probably only works on 32 bit code (64 completely bugs and I cannot test it with my example code).

```c++
                    if (result2) {
                        auto size = arg0->size();
                        auto tmp = temporary(size * 2);
                        auto tmp2 = temporary(size * 2);
                        auto op0 = operand(0);

                        _[
                            tmp2 ^= zero_extend(std::move(op0), size * 2) * zero_extend(resizedRegister(arg0, size), size * 2),
                            tmp ^= tmp2 >> constant(size),
                            regizter(result2) ^= truncate(tmp)
                        ];
                    }
```

For the function (compiled in VS2013 release):

```c++
#include <windows.h>
#include <stdio.h>

int main()
{
    int a;
    int b;
    b = rand();
    a = b / 99;
    printf("a = %d, b = %d", a, b);
    getchar();
}
```

With assembly:

```nasm
01321000 | FF 15 90 20 32 01      | call dword ptr ds:[<&rand>]                | main.cpp:5
01321006 | 8B C8                  | mov ecx,eax                                |
01321008 | B8 03 B5 7E A5         | mov eax,A57EB503                           | main.cpp:9
0132100D | F7 E9                  | imul ecx                                   |
0132100F | 51                     | push ecx                                   | main.cpp:10
01321010 | 03 D1                  | add edx,ecx                                |
01321012 | C1 FA 06               | sar edx,6                                  |
01321015 | 8B C2                  | mov eax,edx                                |
01321017 | C1 E8 1F               | shr eax,1F                                 |
0132101A | 03 C2                  | add eax,edx                                |
0132101C | 50                     | push eax                                   |
0132101D | 68 00 21 32 01         | push intrinsic.1322100                     | 1322100:"a = %d, b = %d"
01321022 | FF 15 98 20 32 01      | call dword ptr ds:[<&printf>]              |
01321028 | 83 C4 0C               | add esp,C                                  |
0132102B | FF 15 8C 20 32 01      | call dword ptr ds:[<&getchar>]             | main.cpp:11
01321031 | 33 C0                  | xor eax,eax                                | main.cpp:12
01321033 | C3                     | ret                                        |
```

I would prefer to implement intrinsic support with arguments so a pseudo `_highmul(arg1, arg2)` can be used instead but I'm not familiar enough with the codebase to get that going.
